version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:7.17.4
    container_name: elasticsearch
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://elasticsearch:9200/_cluster/health?wait_for_status=yellow" ]
      interval: 30s
      timeout: 10s
      retries: 5
  web:
    container_name: docs_manager_web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
       elasticsearch:
         condition: service_healthy
    restart: on-failure
    environment:
      - SPRING_ELASTICSEARCH_URIS=http://elasticsearch:9200
    networks:
      - elastic

networks:
  elastic:
    driver: bridge
volumes:
  esdata: